# FTP Transfer ins WebHosting

name: Deploy via ftp
on: push
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Upload ftp
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: sl233.web.hostpoint.ch
        user: github@modularbeit.ch
        password: githubABBTS2021
        options: "--delete --asci"
